export function createBody(x = -10, z = 18, y = 1) {
  return {
    x,
    y,
    z,
    vx: 0,
    vy: 0,
    vz: 0,
    yaw: Math.PI,
    mode: "land",
    grounded: true,
    slideHeld: false,
    jetHeld: false,
    jetPressTime: 0,
    jetCooldown: 0,
    jetTime: 0,
    hoseActive: false,
    hoseAimX: 0,
    hoseAimY: 0,
    hoseAimZ: -1,
    distance: 0,
    impact: 0,
    resting: false,
  };
}
